#pragma once
#include "dsp_features.h"

enum class KwsClass : uint8_t { SILENCE = 0, UNKNOWN = 1, WAKE_WORD = 2 };

// Loads the INT8 TFLite model (model_weights.h, generated by
// tools/train_and_convert.py — see README) and allocates the tensor arena.
// Call once at boot on Core 0.
void kws_model_init();

// Pushes one feature frame into the model's rolling input window, runs
// inference once the window is full, and applies the 30-frame temporal
// moving average + peak detector (Step 4).
// Returns true exactly once, on the frame where the trigger condition
// (sustained P(wake_word) > TRIGGER_THRESHOLD, then falling) fires.
bool kws_model_push_frame(const FeatureFrame& frame);

// Clears the temporal smoother + peak detector state (Step 7.4 re-arm).
void kws_model_reset();
